#Sonarr Configuration
sonarr:
    server:
        addr:
        port: #Default 8989
        ssl: false 
    auth:
        apikey: 
        username:
        password:
    search: true
    rootFolder: #Path
    seasonFolder: true
    qualityProfileId: #Must be a number

    
  
#Radarr Configuration
radarr:
    server:
        addr:
        port: #Default 7878
        ssl:  false
    auth:
        apikey:
        username:
        password:
    search: true
    rootFolder: #Path
    qualityProfileId: #Must be a number

#Telegram Configuration
telegram:
    token: #Get this from @BotFather
    password:

#Language
language: en #'en' or 'nl'